Adding Slack from Brazil
ParaskP7/android-dev-sources pull request #7
Opened 2017-03-21 18:14 UTC by orafaaraujo

Adding Slack from Brazil, Android Dev Br, the main community of Android developers who lives in Brazil or speak portuguese.

2017-03-21 18:14 UTC, orafaaraujo commented
Adding Slack from Brazil, Android Dev Br, the main community of Android developers who lives in Brazil or speak portuguese

2017-03-21 21:40 UTC, ParaskP7 requested changes

2017-03-21 21:40 UTC, ParaskP7 commented on README.md
> +|  | Android Dev Br | slack.androiddevbr.org |
Can you please change the URL to a Slack URL instead?

androiddevbr.slack.com

2017-03-21 21:42 UTC, ParaskP7 commented
Thank you so much for the contribution Rafael, much appreciated!

Let's keep this baby up-to-date :)

THANK YOU

2017-03-22 11:49 UTC, orafaaraujo reviewed
Updating URL of Android Dev Br

2017-03-22 11:50 UTC, orafaaraujo commented on README.md
> +|  | Android Dev Br | slack.androiddevbr.org |
Hi, @ParaskP7 
Done!

2017-03-22 11:52 UTC, orafaaraujo commented
You're welcome, @ParaskP7 :)

If the community goes well everybody wins!

2017-03-22 19:13 UTC, ParaskP7 approved these changes

2017-03-22 19:13 UTC, merged

2017-03-22 19:15 UTC, ParaskP7 commented
Exactly!